- id: 1
  code: ICBC
  name: 工商银行
- id: 2
  code: CBC
  name: 中国建设银行
- id: 3
  code: BC
  name: 中国银行
- id: 4
  code: BCM
  name: 交通银行
- id: 5
  code: ABC
  name: 中国农业银行
- id: 6
  code: CMBC
  name: 招商银行
- id: 7
  code: CMBC
  name: 民生银行
- id: 8
  code: CNCB
  name: 中信银行
- id: 9
  code: HXB
  name: 华夏银行
- id: 10
  code: CIB
  name: 兴业银行
- id: 11
  code: SPDB
  name: 上海浦东发展银行
- id: 12
  code: BOB
  name: 北京银行
- id: 13
  code: CNCB
  name: 中信银行
- id: 14
  code: CEB
  name: 中国光大银行
- id: 15
  code: SDB
  name: 深圳发展银行
- id: 16
  code: GDB
  name: 广东发展银行
