- id: 200
  key: satoshi
  currency: btc
  min_confirm: 1
  max_confirm: 6
- id: 400
  key: bank
  currency: cny
  banks: ["icbc", "cmb", "abc", "cbc", "bc", "cmbc", "ceb", "cncb", "bcm", "cib", "spdb", "hxb", "pab", "gdb", "bob"]
- id: 500
  key: protoshare
  currency: pts
  min_confirm: 1
  max_confirm: 6
