- id: 200
  key: satoshi
  currency: btc
  min_confirm: 1
  max_confirm: 6
- id: 400
  key: bank
  currency: cny
  banks: ['cmbc', 'bcm', 'cncb', 'hxb', 'cib', 'spdb', 'bob', 'cncb', 'ceb', 'sdb', 'gbd', 'cmb', 'icbc', 'abc', 'bc', 'cbc']
