- id: 200
  key: satoshi
  currency: btc
  fixed: 4
  fee: 0.0001
  sort_order: 2
- id: 300
  key: protoshare
  currency: pts
  fixed: 4
  fee: 0.0001
  sort_order: 3
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 100
  max: 50000
  fee: 0
  proportion: true
  inuse: true
  type: WithdrawChannelBank
  sort_order: 4
- id: 500
  key: dogecoin
  currency: dog
  fixed: 4
  fee: 0.0001
  sort_order: 1
