- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0001
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 1
  max: 50000
  fee: 0
  proportion: true
  inuse: true
  banks: ["icbc", "cmb", "abc", "cbc", "bc", "cmbc", "ceb", "cncb", "bcm", "cib", "spdb", "hxb", "pab", "gdb", "bob"]
  type: WithdrawChannelBank


