- id: 200
  key: satoshi
  currency: btc
  fixed: 8
  fee: 0.0001
  inuse: true
  type: WithdrawChannelSatoshi
- id: 400
  key: bank
  currency: cny
  fixed: 2
  fee_max: 0
  min: 1
  max: 50000
  fee: 0
  proportion: true
  inuse: true
  banks: ["icbc", "cbc", "bc", "bcm", "abc", "cmb", "cmbc", "cncb", "hxb", "cib", "spdb", "bob", "cncb", "ceb", "sdb", "pab", "gdb"]
  type: WithdrawChannelBank
